[project]
name = "mcp-kit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.12.3",
    "openai>=1.107.2",
    "psycopg2-binary>=2.9.10",
]
